min_trimmed_length = 1
min_word_count = 1
max_word_count = 100
min_characters = 1
may_end_with_colon = true
quote_start_with_letter = false
needs_punctuation_end = false
needs_letter_start = false
needs_uppercase_start = false
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

